export type ReducerStoreAndDispatch<StateType, ActionType> = import("reshow-flux-base").ReducerStoreAndDispatch<StateType, ActionType>;
export type ReducerType<StateType, ActionType> = import("reshow-flux-base").ReducerType<StateType, ActionType>;
export type DispatchFunction<StateType, ActionType> = import("reshow-flux-base").DispatchFunction<StateType, ActionType>;
export type StoreObject<StateType, ActionType> = import("reshow-flux-base").StoreObject<StateType, ActionType>;
export const localStorageStore: StoreObject<Storage, any>;
export const localStorageDispatch: DispatchFunction<Storage, any>;
export const localValueStore: StoreObject<Storage, any>;
export const localValueDispatch: DispatchFunction<Storage, any>;
export const sessionStorageStore: StoreObject<Storage, any>;
export const sessionStorageDispatch: DispatchFunction<Storage, any>;
export const sessionValueStore: StoreObject<Storage, any>;
export const sessionValueDispatch: DispatchFunction<Storage, any>;
import { Storage } from "get-storage";
